// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProblemCrawler.Infrastructure.Data;

#nullable disable

namespace ProblemCrawler.Infrastructure.Migrations
{
    [DbContext(typeof(ProblemCrawlerDbContext))]
    [Migration("20260323111733_MoveThreadRootToAnalysedRootCollector")]
    partial class MoveThreadRootToAnalysedRootCollector
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.AnalysedItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionabilityRationale")
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .HasColumnType("text");

                    b.Property<DateTime>("AnalyzedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CollectorItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<bool>("ContainsProblem")
                        .HasColumnType("boolean");

                    b.Property<string>("CurrentWorkaround")
                        .HasColumnType("text");

                    b.Property<string>("DesiredOutcome")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActionable")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("PainLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ProblemDetails")
                        .HasColumnType("text");

                    b.Property<string>("ProblemSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RootCollectorItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SoftwareOpportunity")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrgencySignal")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedAtUtc");

                    b.HasIndex("CollectorItemId")
                        .IsUnique();

                    b.HasIndex("Industry");

                    b.HasIndex("IsActionable");

                    b.HasIndex("RootCollectorItemId");

                    b.ToTable("AnalysedItems", (string)null);
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.CollectorItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkId")
                        .HasColumnType("text");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "Source")
                        .IsUnique();

                    b.ToTable("CollectorItems");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.AnalysedItemEntity", b =>
                {
                    b.HasOne("ProblemCrawler.Infrastructure.Entities.CollectorItemEntity", "CollectorItem")
                        .WithOne("AnalysedItem")
                        .HasForeignKey("ProblemCrawler.Infrastructure.Entities.AnalysedItemEntity", "CollectorItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProblemCrawler.Infrastructure.Entities.CollectorItemEntity", null)
                        .WithMany()
                        .HasForeignKey("RootCollectorItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectorItem");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.CollectorItemEntity", b =>
                {
                    b.Navigation("AnalysedItem");
                });
#pragma warning restore 612, 618
        }
    }
}
