// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using ProblemCrawler.Infrastructure.Data;

#nullable disable

namespace ProblemCrawler.Infrastructure.Migrations
{
    [DbContext(typeof(ProblemCrawlerDbContext))]
    [Migration("20260419202110_AddLabelToProblemCluster")]
    partial class AddLabelToProblemCluster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.AnalysedItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionabilityRationale")
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .HasColumnType("text");

                    b.Property<DateTime>("AnalyzedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CollectorItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<bool>("ContainsProblem")
                        .HasColumnType("boolean");

                    b.Property<string>("CurrentWorkaround")
                        .HasColumnType("text");

                    b.Property<string>("DesiredOutcome")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActionable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSynthesisInProgress")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSynthesized")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("PainLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ProblemDetails")
                        .HasColumnType("text");

                    b.Property<string>("ProblemSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RootCollectorItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SoftwareOpportunity")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SynthesisClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrgencySignal")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedAtUtc");

                    b.HasIndex("CollectorItemId")
                        .IsUnique();

                    b.HasIndex("Industry");

                    b.HasIndex("IsActionable");

                    b.HasIndex("RootCollectorItemId");

                    b.ToTable("AnalysedItems", (string)null);
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ClusterRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MinClusterSize")
                        .HasColumnType("integer");

                    b.Property<int?>("MinSamples")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ClusterRun", (string)null);
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.CollectorItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkId")
                        .HasColumnType("text");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "Source")
                        .IsUnique();

                    b.ToTable("CollectorItems");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ProblemClusterArchiveEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AvgConfidence")
                        .HasColumnType("real");

                    b.Property<int>("ClusterId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClusterRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClusterRunId");

                    b.ToTable("ProblemClusterArchive", (string)null);
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ProblemClusterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AvgConfidence")
                        .HasColumnType("real");

                    b.Property<int>("ClusterId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClusterRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<string>("Opportunity")
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClusterRunId");

                    b.ToTable("ProblemCluster", (string)null);
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ThreadSynthesisRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnalysedItemCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AnalyzedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LatestAnalysedItemUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LatestCollectorItemCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RootCollectorItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("ThreadItemCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedAtUtc");

                    b.HasIndex("RootCollectorItemId");

                    b.ToTable("ThreadSynthesisRuns", (string)null);
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ThreadSynthesizedIdeaEmbeddingArchiveEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("ClusterConfidence")
                        .HasColumnType("real");

                    b.Property<int?>("ClusterId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClusterRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector");

                    b.Property<string>("IdeaSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ThreadSynthesizedIdeaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClusterRunId");

                    b.HasIndex("ThreadSynthesizedIdeaId");

                    b.ToTable("ThreadSynthesizedIdeaEmbeddingArchive", (string)null);
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ThreadSynthesizedIdeaEmbeddingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("ClusterConfidence")
                        .HasColumnType("real");

                    b.Property<int?>("ClusterId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClusterRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ThreadSynthesizedIdeaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClusterRunId");

                    b.HasIndex("ThreadSynthesizedIdeaId")
                        .IsUnique();

                    b.HasIndex("ThreadSynthesizedIdeaId", "Model")
                        .IsUnique();

                    b.ToTable("ThreadSynthesizedIdeasEmbedding");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ThreadSynthesizedIdeaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionabilityRationale")
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .HasColumnType("text");

                    b.Property<DateTime>("AnalyzedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentWorkaround")
                        .HasColumnType("text");

                    b.Property<string>("DesiredOutcome")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActionable")
                        .HasColumnType("boolean");

                    b.Property<string>("ProblemDetails")
                        .HasColumnType("text");

                    b.Property<string>("ProblemSummary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("SoftwareOpportunity")
                        .HasColumnType("boolean");

                    b.Property<int>("SupportingDistinctAuthorCount")
                        .HasColumnType("integer");

                    b.Property<int>("SupportingMentionCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ThreadSynthesisRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrgencySignal")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedAtUtc");

                    b.HasIndex("Industry");

                    b.HasIndex("IsActionable");

                    b.HasIndex("ThreadSynthesisRunId");

                    b.ToTable("ThreadSynthesizedIdeas", (string)null);
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.AnalysedItemEntity", b =>
                {
                    b.HasOne("ProblemCrawler.Infrastructure.Entities.CollectorItemEntity", "CollectorItem")
                        .WithOne("AnalysedItem")
                        .HasForeignKey("ProblemCrawler.Infrastructure.Entities.AnalysedItemEntity", "CollectorItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProblemCrawler.Infrastructure.Entities.CollectorItemEntity", null)
                        .WithMany()
                        .HasForeignKey("RootCollectorItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectorItem");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ProblemClusterArchiveEntity", b =>
                {
                    b.HasOne("ProblemCrawler.Infrastructure.Entities.ClusterRunEntity", "ClusterRun")
                        .WithMany()
                        .HasForeignKey("ClusterRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterRun");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ProblemClusterEntity", b =>
                {
                    b.HasOne("ProblemCrawler.Infrastructure.Entities.ClusterRunEntity", "ClusterRun")
                        .WithMany("ProblemClusters")
                        .HasForeignKey("ClusterRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterRun");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ThreadSynthesisRunEntity", b =>
                {
                    b.HasOne("ProblemCrawler.Infrastructure.Entities.CollectorItemEntity", null)
                        .WithMany()
                        .HasForeignKey("RootCollectorItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ThreadSynthesizedIdeaEmbeddingArchiveEntity", b =>
                {
                    b.HasOne("ProblemCrawler.Infrastructure.Entities.ClusterRunEntity", "ClusterRun")
                        .WithMany()
                        .HasForeignKey("ClusterRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterRun");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ThreadSynthesizedIdeaEmbeddingEntity", b =>
                {
                    b.HasOne("ProblemCrawler.Infrastructure.Entities.ClusterRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ClusterRunId");

                    b.HasOne("ProblemCrawler.Infrastructure.Entities.ThreadSynthesizedIdeaEntity", "Idea")
                        .WithOne("Embedding")
                        .HasForeignKey("ProblemCrawler.Infrastructure.Entities.ThreadSynthesizedIdeaEmbeddingEntity", "ThreadSynthesizedIdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ThreadSynthesizedIdeaEntity", b =>
                {
                    b.HasOne("ProblemCrawler.Infrastructure.Entities.ThreadSynthesisRunEntity", "ThreadSynthesisRun")
                        .WithMany("Ideas")
                        .HasForeignKey("ThreadSynthesisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThreadSynthesisRun");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ClusterRunEntity", b =>
                {
                    b.Navigation("ProblemClusters");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.CollectorItemEntity", b =>
                {
                    b.Navigation("AnalysedItem");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ThreadSynthesisRunEntity", b =>
                {
                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("ProblemCrawler.Infrastructure.Entities.ThreadSynthesizedIdeaEntity", b =>
                {
                    b.Navigation("Embedding");
                });
#pragma warning restore 612, 618
        }
    }
}
